language: R
sudo: false
cache: packages
warnings_are_errors: true
after_success:
    - Rscript -e 'covr::coveralls()'
addons:
  apt:
    packages:
      - libudunits2-dev
before_install:
  - sudo add-apt-repository ppa:ubuntugis/ppa --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev
