language: r
cache: packages
warnings_are_errors: true

addons:
    apt:
        packages:
            - libgdal-dev
            - libudunits2-dev
            - libnetcdf-dev
            - netcdf-bin

r_packages:
    - rgdal
    - sf
    - lwgeom
