language: r
cache: packages
warnings_are_errors: true
dist: bionic

addons:
    apt:
        packages:
            - libgdal-dev
            - libudunits2-dev

r_packages:
    - rgdal
    - sf
    - lwgeom
