# References

- Biljecki, F., Ledoux, H., & van Oosterom, P. (2013). Transportation
  mode-based segmentation and classification of movement
  trajectories. International Journal of Geographical Information
  Science, 27, 385–407. https://dx.doi.org/10.1080/13658816.2012.692791

- Calenge, C., Dray, S., & Royer-Carenzi, M. (2009). The concept of
  animals' trajectories from a data analysis perspective. Ecological
  Informatics, 4,
  34–41. https://dx.doi.org/10.1016/j.ecoinf.2008.10.002

- Gudmundsson, J., Laube, P., & Wolle, T. (2011). Computational
  Movement Analysis. *In* Kresse W, & Danko D. M. (Eds.), Springer
  Handbook of Geographic Information (pp. 423–438), Springer-Verlag
  Berlin Heidelberg. https://dx.doi.org/10.1007/978-3-540-72680-7_22

- Joo, R., Boone, M. E., Clay, T. A., Patrick, S. C.,
  Clusella-Trullas, S., & Basille, M. (2018). Navigating through the R
  packages for movement. arXiv, 1901.05935,
  https://arxiv.org/abs/1901.05935

- Martin, J., Tolon, V., Van Moorter, B., Basille, M., & Calenge,
  C. (2009). On the use of telemetry in habitat selection studies. *In*
  D. Barculo, & Daniels J. (Eds.), Telemetry: Research, Technology and
  Applications (pp. 37–55), Nova Science Publishers Inc.

- Roswell, C. (2011). Modeling of geographic information. *In* Kresse
  W, & Danko D. M. (Eds.), Springer Handbook of Geographic Information
  (pp. 3–6), Springer-Verlag Berlin
  Heidelberg. https://dx.doi.org/10.1007/978-3-540-72680-7_1

- Turchin, P. (1998). Quantitative analysis of movement: measuring and
  modeling population redistribution in animals and plants. Sinauer
  Associates.
