# Requirements
<!-- 
An idea of what is required to make the project actually happen
-->

## People
<!--
Who needs to be involved, what's the proposed structure, what will it take to get their involvement?
-->

The core project team, and primarily Matt Boone, will initiate and
lead the necessary consultation, code the proposed package, implement
the data model, and ensure successful outcome of the project. All
contributors to the proposal and people who have been consulted for it
(listed above), and more broadly the entire community working on
movement, will also be consulted during the different phases of the
work, and will be invited to contribute further to the realization of
the project.

In particular, we request \$10,000 in salary for 1.84 months of Matt
Boone, Data Scientist at the University of Florida. Matt has a solid
experience in R, and will be the main developer and contributor to the
codebase. As all other contributions will be in-kind, having Matt
fully dedicated ensures successful completion of the project.


## Processes
<!-- 
What processes need to be put in place e.g. codes of conduct, regular ISC meetings, handover to the community at large?
-->

As this project ultimately aims at building a R Movement community, we
will adopt a community-based code of conduct. The recently updated
[code of conduct of rOpenSci](https://ropensci.org/code-of-conduct/)
will serve as a basis, as we share foundational values of openness,
tolerance and inclusiveness.

As we want this project to be as open as possible, we will adopt a
"release early, release often" philosophy to provide most recent
developments to the community, and allow for early testing of the
`sftraj` package.  At all stages but especially at the first one (*Use
cases*), we will seek feedback from the Movement community. While
working on the review of R tracking packages, we have been successful
in mobilizing the Movement community through Twitter notably; for
instance, 225 persons filled out our survey on package usage and
documentation. We will use this already established connection to
reach out further, and invite the largest number of people to
contribute and provide feedback. Public development on GitHub will
allow the use of the issue system to initiate and discuss each use
case with and from the community.


## Tools & Tech
<!--
What is going to be needed to deliver this project? 

Will cloud computing be used - if yes are there are necessary components that will be deciding factors between providers?

Are there tools or tech that don't exist that will be produced to facilitate the project?
-->

No technical constraint is foreseen. All team members are already
equipped with enough computer power to work on the project.  The
development platform (GitHub) is already set up and public, and will
remain open to the entire Movement community.


## Funding
<!-- 
[TO DO] THE GUIDANCE IS PRETTY UNCLEAR, ESP IN LIGHT OF GABOR'S PROPOSAL VS AWARD SIZE

-->

We request a total of \$10,000 to support 1.84 months of Matt Boone,
Data Scientist (Biological Scientist II) in the MabLab at the
University of Florida.

* Salary: \$7,369
* Fringe rate (35.70 %): \$2,631
* **Total award = \$10,000**

<!-- We request a total of \$7,457 to support 0.115 FTE (6 weeks) of Matt -->
<!-- Boone, Data Scientist (Biological Scientist II) in the MabLab at the -->
<!-- University of Florida. -->

<!-- * Salary: \$5,495 -->
<!-- * Fringe rate (35.70 %): \$1,962 -->
<!-- * **Direct total cost**: \$7,457 -->
<!-- * Indirect cost (34.1 %): \$2,543 -->
<!-- * **Total award**: \$10,000 -->


## Summary
<!--
A summary of the requirements that contextualises the costs
-->

Salary to support a Data Scientist is requested to have one person
committed to the project, who will dedicate set chunks of time to the
work. This seems required to ensure project completion in the proposed
timeline. Almost 8 weeks of work is a reasonable amount of time, which
matches proposed deliverables. All other contributions, from core team
members and other contributors, will be in-kind.
