# Signatories
<!-- 
This section provides the ISC with a view of the support received from the community for a proposal. Acceptance isn't predicated on popularity but community acceptance is important.  Willingness to accept outside input is also a good marker for project delivery. 

An optional section would be for R-Core signatories where changes to R are proposed.
-->

The **Project team** lists the core members of the work, who will be
instrumental in progress and completion of the
project. **Contributors** actively helped with this proposal, and
**Consulted** have been given the opportunity to provide
feedback. Signatories are listed by alphabetical order.  **Note:
relevant R packages to which people contributed are indicated within
brackets.**

## Project team
<!-- 
Who are the people responsible for actually delivering the project if the proposal gets accepted and are already signed up and rearing to go?
-->

  * **Mathieu Basille**, Assistant Professor at the University of
    Florida, USA [`hab`, `rpostgis`, `rpostgisLT`]
  * **Matt Boone**, Data Scientist at the University of Florida, USA
  * **Clément Calenge**, Statistical analyst at the *Office national
    de la chasse et de la faune sauvage*, France [`adehabitatHR`,
    `adehabitatLT`]
  * **Rocío Joo**, Postdoctoral Associate at the University of
    Florida, USA
  * **Emiel van Loon**, Assistant Professor at the University of
    Amsterdam, the Netherlands.


## Contributors
<!-- 
Who are the people who have actively helped with this proposal but won't necessarily be on the core project team later?
-->

  * **Balázs Dukai**, Delft University of Technology, the Netherlands
    [`rpostgisLT`]
  * **Ioannis Kosmidis**, University of Warwick, UK [`trackeR`]
  * **Bart Kranstauber**, University of Zurich, Switzerland [`move`]
  * **Edzer Pebesma**, University of Munster, Germany[`sf` and
    `trajectories`]


## Consulted
<!-- 
Who has been given the opportunity to provide feedback on the proposal? This should include any R Consortium & ISC members who the proposal has been discussed with.
-->

  * **Francesca Cagnacci**, Edmund Mach Foundation, Italy
  * **Hamish Campbell**, Charles Darwin University, Australia
    [`VTrack`]
  * **Ross Dwyer**, University of Queensland, Australia [`Digiroo2`,
    `VTrack`]
  * **Brett McClintock**, University of St. Andrews, Scotland
    [`moveHMM`, `momentuHMM`]
  * **Théo Michelot**, University of St. Andrews, Scotland [`moveHMM`,
    `momentuHMM`]
  * **Henning Teickner**, University of Munster, Germany
  * **Vinay Udyawer**, Australian Institute of Marine Science,
    Australia [`VTrack`]
  * **Ferdinando Urbano**, Freelancer, Italy

From the R Consortium:

  * **Hadley Wickham**
