# Success
<!-- 
Projects should have a definition of done that is measurable, and a thorough understanding going in of what the risks are to delivery 
-->

## Definition of done
<!-- 
What does success look like? 
-->

This project will be successful if a functional R package (`sftraj`)
that provides usable classes for tracking and movement data is
available at the end of the 6 months period. This will pave the way
for further consolidation and adoption by the Movement community in
the next stages of the `sftraj` project.


## Measuring success
<!-- 
How will we know when success is achieved, what markers can we use along the way 
-->

Success can be measured by the completion of deliverables through
time, as set up in the *Project plan* section (see notably the minimum
viable product). Beyond deliverables, success can also be measured
both during and after the period of work by the adoption by the
Movement community:

  * **During the work:**
    * Contributions of the Movement community during the early stage
      (*use cases*): number of contributors and contributions;
    * Beta testing from the Movement community: number of testers and
      issues submitted;
    * Code contribution: number of contributors and contributions.
  * **After the work: **
    * From a user perspective: number of downloads (e.g. using RStudio
      download statistics);
    * From a developer perspective: adoption in tracking packages.


## Future work
<!-- 
How could this be extended / developed in the future by yourself and/or the community in general?
-->

The long-term plan for `sftraj` includes major steps relying on the
availability of a functional trajectory package. Future stages of
development already include:

  * Full-fledged package: submission to
    [CRAN](https://cran.r-project.org/) and to
    [rOpenSci](https://ropensci.org/).
  * Preparation of a detailed article to present the technical choices
    and the solution offered by `sftraj`, in order to favor adoption
    by users and package developers. Prepared for the R Journal.
  * Keep the conversation open with package developers, and help them
    developing conversion tools to main existing classes.
  * Dynamic visualization of trajectories, allowing keyboard- and
    mouse-controlled exploration of trajectories, step by step (based
    on the solution provided in `rpostgisLT`).

Other avenues of development to be explored further include:

  * Supporting measurement units and errors, and their propagation, in
    the spatial components of the trajectories, i.e. making the
    package `units` and `errors` compliant.
  * Developing tools to clean and interpolate trajectories, based on
    specific filters and assumptions.


## Key risks
<!-- 
What sort of things could come up that can delay or break the project?

 - [ ] People
 - [ ] Processes
 - [ ] Tooling & Technology
 - [ ] Costs

-->

Delays on the project could happen because of community feedback that
requires reformating classes or halting it altogether because of a
lack of consensus.  This can be mitigated by making sure the Movement
community is largely involved and consulted at every stage of the
project. This is a fundamental aspect of our approach.

Technically, the main hurdles may deal with the structure of `sf`
objects, which, if not resolved directly, may require the consultation
and/or collaboration of Edzer Pebesma, author of the `sf` package, who
contributed to the development of this proposal.

Finally, there are inherent risks related to unforeseen problems that
will arise and the extra time necessary to address them. This project
has been framed with discrete manageable goals for every month of the
period of work. Using the MoSCoW method, we defined reasonable
deliverables, as well as optional and desirable requirements if time
allows. We also made sure to keep unrealistic requirements out of the
scope of this grant (see *Future work* above).
