# Project plan

## Start-up phase
<!--
Covering the planning phase, this section should provide a relatively detailed plan of how work will start on the project. This section is important because projects need to get up and running quickly.


 - [ ] Setting up collaboration platform inc. code for contributors etc.
 - [ ] Licence decisions
 - [ ] Reporting framework
-->

The `sftraj` package is meant to be a cornerstone for the development
of a more cohesive Movement community in R. For this to happen, we
will involve all voluntary contributors from the community, and work
in the open all along. For instance, a collaborative platform already
in place relies on a public [GitHub
repository](https://github.com/mablab/sftraj). We will add a code of
conduct based on the principles of
[rOpenSci](https://ropensci.org/code-of-conduct/) to ensure a good
collaborative environment, and adopt the MIT license for the package,
as to allow wide acceptation by other package developers.

The first stage of the work (see timeline below) will specifically
involve the Movement community in R. During this stage, we will open
contributions of *use cases* for the package (using GitHub's issue
system), which set practical goals for the development of the
package. Use cases describe the workflow that is expected from both
users' and developers' perspectives, and thus the capabilities that a
trajectory package needs to offer.  Once all use cases will be
available, the package specifications and development will aim at
addressing them all, to make sure the solution provided is relevant
for a wide array of users and package developers.

<!-- For instance, a new object that sets the standards for -->
<!-- trajectory data from the perspective of the `trackeR` package should -->
<!-- have the following features: -->

<!--   1. can carry all recorded movement information (time, longitude, -->
<!--      latitude, speed, distance, altitude); -->
<!--   2. have methods that allow the user to -->
<!--     - infer speed from distance and time (and elevation for 3D) -->
<!--     - infer distance from speed and time (and elevation for 3D) -->
<!--     - infer distance and speed from time, lon, lat, altitude (and -->
<!--       elevation for 3D) -->
<!--     - impute speed/distance from past/future observations if time, -->
<!--       lon, lat are missing -->
<!--     - correct altitude data (for 2D) -->
<!--     - correct coordinate data (by smoothing) -->
<!--   3. is unit-aware (for speed, distance, altitude) and allows changing -->
<!--      those units; -->
<!--   4. allows for extra variables (e.g. power, cadence and the likes in -->
<!--   5. the context of athlete trajectories) that are recorded at -->
<!--      timestamp level; -->
<!--   6. allow for variables that are recorded at trajectory level -->
<!--      (e.g. athlete name and sport), without having to repeat that over -->
<!--      all timestamps in a trajectory. -->


## Technical delivery
<!--
Covering the actual delivery of the project this section should provide at least a high-level the implementation. 

Including target dates is really important as you need to be committed and the ISC need to have a means of tracking delivery
-->

The time frame of this project is over 6 months.  We used the MoSCoW
method to determine what will be delivered from this project, starting
from a minimum viable product to future development:

  * **Must have** (requirements necessary for project completion,
    i.e. the minimum viable product)
    * Use cases defined [month 1–2]
    * Data model revisited and classes definition [month 3]
    * Creators and converters from basic objects (`data.frames`, `sf`,
      `sftrack`, `sftraj`) [month 4]
    * Installable package (GitHub) [months 4–6]
    * Accessors and summaries (`print`, `summary`) [month 5]
    * Full function documentation and unit testing [months 5–6]
  * **Should have** (important requirements not necessary for project
    completion):
    * Vignette [month 6]
  * **Could have** (desirable requirements developed if time allows):
    * CRAN package
    * Basic plot (static)
  * **Won't have** (requirements that are not planned at this stage):
    * See section on *Future work*.


## Other aspects
<!--
Covering non-technical activities like on-going publicity, paper preparation, discussion groups etc. that might be required to facilitate successful delivery of the project.

 - [ ] Announcement post
 - [ ] Delivery blog post
 - [ ] Twitter
 - [ ] UseR!
 - [ ] ISC meetings
-->

We will publicly provide developments of new ideas and functions
through regular blog posts on the [MabLab
website](https://mablab.org/) to communicate progress (basically for
each stage and deliverable), and constant communication on Twitter by
the core team. Twitter and emails will also be largely used to reach
out to the community, as we have successfully done in the past for the
R tracking package review (Joo *et al.* 2019) and the Movement Ecology
synthesis (Joo *et al.* *in prep*).
